# Generated by Django 5.1.2 on 2024-11-10 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_printcost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printcostconfig',
            name='cost_per_page',
        ),
        migrations.RemoveField(
            model_name='printcostconfig',
            name='type',
        ),
        migrations.RemoveField(
            model_name='printrequest',
            name='cost_estimate',
        ),
        migrations.AddField(
            model_name='printcostconfig',
            name='black_white_print_cost',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='printcostconfig',
            name='color_print_cost',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='printcostconfig',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PrintCost',
        ),
    ]
