# Generated by Django 5.1.2 on 2024-11-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_printcostconfig_cost_per_page_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintCostConfig',
        ),
    ]
