# Generated by Django 5.1.2 on 2024-11-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_printcostconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_print_cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('black_white_print_cost', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ownerprofile')),
            ],
        ),
    ]
